spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 30de19480357dbd1c8fe
            clientSecret: ${clientSecret1} # прячем пароли в идее чтобы не выливать их в сеть
          google:
            clientId: 1050798306038-8vnht4ms6aitr6rujbd5magbohrih2d4.apps.googleusercontent.com
            clientSecret: ${clientSecret2}